.\"
.\"  This manual page section is maintained by Michael Meifert,
.\"  <mime@dk3hg.hanse.de>. Since this information is availabe
.\"  by readind the documentation files, I don't intend to work
.\"  on the man pages this time. 
.\"
.\"  Thanks for his work on this documentaion file !
.\"
.\"
.\"
.\"
.Id $Id: cstat.1,v 1.1.1.1 2001/11/05 23:06:25 dl9sau Exp $
.TH CSTAT 1 "May 1994" local "Ping-Pong Convers Manual"
.SH NAME
cstat \- shows convers connect status 
.SH SYNOPSIS
.B cstat
.SH DESCRIPTION
.B cstat
shows the connect status of all host convers daemons.
.SH OPTIONS
None.
.SH WARNINGS
None.
.SH FILES
.B /usr/local/spool/convers/sockets/convers [/tcp/sockets/convers]
conversd unix domain socket for connections
.SH SEE ALSO
convers(1), online(1), conversd(8)
.SH AUTHORS
Ping-Pong convers was written by Fred Baumgarten
(dc6iq@insl1.etec.uni-karlsruhe.de). Manual page by Michael Meifert
(mime@dk3hg.hanse.de).
