const fim_char_t * const FIM_DEFAULT_EXAMPLE_FILE_CONTENTS =
"# jump to the third image:\n"
"3;\n"
"# jump to first image:\n"
"^;\n"
"# jump to last image:\n"
"$;\n"
"# magnify the image two times:\n"
"*2;\n"
"# scale the image to the 30% of the original:\n"
"30%;\n"
"# scale the image up by 30%:\n"
"+30%;\n"
"# scale the image down by 30%:\n"
"-30%;\n"
"# jump to the next image whose filename matches the \".*jpg\" regular expression:\n"
"/.*jpg;\n"
"# execute the \"date\" system command\n"
"!\"date\";\n"
"";
