//#ifdef FIM_WANT_INLINE_HELP

#define FIM_AUTOCOMMANDS_LIST \
FIM_ACM_PRESCALE", " FIM_ACM_POSTSCALE", " FIM_ACM_PREPAN", " FIM_ACM_POSTPAN", " FIM_ACM_PREREDISPLAY", " FIM_ACM_POSTREDISPLAY", " FIM_ACM_PREDISPLAY", " FIM_ACM_POSTDISPLAY", " FIM_ACM_PREPREFETCH", " FIM_ACM_POSTPREFETCH", " FIM_ACM_PRERELOAD", " FIM_ACM_POSTRELOAD", " FIM_ACM_PRELOAD", " FIM_ACM_POSTLOAD", " FIM_ACM_PREGOTO", " FIM_ACM_POSTGOTO", " FIM_ACM_PRECONF", " FIM_ACM_POSTCONF", " FIM_ACM_PREHFIMRC", " FIM_ACM_POSTHFIMRC", " FIM_ACM_PREUFIMRC", " FIM_ACM_POSTUFIMRC", " FIM_ACM_PREGFIMRC", " FIM_ACM_POSTGFIMRC", " FIM_ACM_PREINTERACTIVECOMMAND", " FIM_ACM_POSTINTERACTIVECOMMAND", " FIM_ACM_PREEXECUTIONCYCLE", " FIM_ACM_POSTEXECUTIONCYCLE", " FIM_ACM_PREEXECUTIONCYCLEARGS", " FIM_ACM_PREWINDOW", " FIM_ACM_POSTWINDOW", "  
//#endif
