:macro cexit
;;
;; cexit.mac - this macro is called automatically when any channel
;;             disconnects
;;
;; Parametres: %1 - callsign of disconnected station
;;

;; When a path to logbook is set, complete a logbook entry
if %(exist LOG_PATH@0) == 1
  if %(exist LOG_QRG) == 1
    log stop %LOG_PATH@0/%Y %1 "%LOG_QRG"
  endif
endif

;; Clear acces list
rcmd ""

;; Switch off the compression
compress off
