
LinPac: Verbundene Stationen:

 Kanal    Port   Rufzeichen Name
:set CHN 1
:label RPT
:IF %(iscon@%CHN) != 0
:set PNUM %P@%CHN
:set PNAME %(get@0 _port_name_%PNUM)
:IF %N@%CHN != %C@%CHN
    %(strf R 2 %CHN)    %(strf L 6 %PNAME) %(strf L 10 %C@%CHN) %N@%CHN
:ELSE
    %(strf R 2 %CHN)    %(strf L 6 %PNAME) %(strf L 10 %C@%CHN)
:ENDIF
:ENDIF
:set CHN %[%CHN+1]
:IF %CHN <= %_maxchn@0
:GOTO RPT
:ENDIF

:unset CHN
:unset PNUM
:unset PNAME
